wandb_version: 1

coral_wt:
  desc: null
  value: 2.190661254576351
lr:
  desc: null
  value: 0.005
_fields:
  desc: null
  value:
    coral_wt: 7.290929120867309
    lr: 0.001
    Dataset_Name: PU_Real
    Scenarios:
    - - Normal
      - Rotate
      - Load
      - Radial
    num_class: 5
    input_channel: 1
    Backbone_Type: CNN
    feature_length: 5
    hidden_channels: 64
    kernel_size: 5
    stride: 1
    dropout: 0.5
    output_channels: 128
    hidden_layers: 5
    Classifier_Type: Classifier
    input_size: 640
    n_epoch: 1
    momentum: 0.9
    weight_decay: 0.0001
    step_size: 50
    gamma: 0.5
    algo_configs: 'Method: SHOT

      ent_loss_wt: 0.8467

      im: 0.2983

      target_cls_wt: 1

      '
_locked:
  desc: null
  value: false
_type_safe:
  desc: null
  value: true
_convert_dict:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696392843.529873
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
