wandb_version: 1

coral_wt:
  desc: null
  value: 7.966732325543671
lr:
  desc: null
  value: 0.01
_items:
  desc: null
  value:
    coral_wt: 5.3274778005759025
    lr: 0.005
    _items:
      coral_wt: 0.6353873203309846
      lr: 0.005
      Dataset_Name: PU_Real
      Scenarios:
      - - Normal
        - Rotate
        - Load
        - Radial
      num_class: 5
      input_channel: 1
      Backbone_Type: CNN
      feature_length: 5
      hidden_channels: 64
      kernel_size: 5
      stride: 1
      dropout: 0.5
      output_channels: 128
      hidden_layers: 5
      Classifier_Type: Classifier
      input_size: 640
      n_epoch: 1
      momentum: 0.9
      weight_decay: 0.0001
      step_size: 50
      gamma: 0.5
      _wandb: {}
    _locked:
      coral_wt: 0
      lr: 0
    _users:
      sweep: 0
    _users_inv:
      '0': sweep
    _users_cnt: 1
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _settings:
      _args: []
      _aws_lambda: false
      _async_upload_concurrency_limit: null
      _cli_only_mode: null
      _colab: false
      _cuda: null
      _disable_meta: false
      _disable_service: false
      _disable_setproctitle: false
      _disable_stats: false
      _disable_viewer: null
      _disable_machine_info: false
      _except_exit: true
      _executable: C:\Users\Mohamed Ragab\.conda\envs\dl_work\python.exe
      _extra_http_headers: null
      _file_stream_retry_max: 125
      _file_stream_retry_wait_min_seconds: 2
      _file_stream_retry_wait_max_seconds: 60
      _file_stream_timeout_seconds: 180
      _file_uploader_retry_max: 10
      _file_uploader_retry_wait_min_seconds: 2
      _file_uploader_retry_wait_max_seconds: 60
      _file_uploader_timeout_seconds: 0
      _flow_control_custom: false
      _flow_control_disabled: false
      _graphql_retry_max: 10
      _graphql_retry_wait_min_seconds: 2
      _graphql_retry_wait_max_seconds: 60
      _graphql_timeout_seconds: 30
      _internal_check_process: 8.0
      _internal_queue_timeout: 2.0
      _ipython: false
      _jupyter: false
      _jupyter_name: null
      _jupyter_path: null
      _jupyter_root: null
      _kaggle: false
      _live_policy_rate_limit: null
      _live_policy_wait_time: null
      _log_level: 10
      _network_buffer: null
      _noop: false
      _notebook: false
      _offline: false
      _sync: false
      _os: Windows-10-10.0.19045-SP0
      _platform: windows
      _proxies: null
      _python: 3.9.13
      _runqueue_item_id: null
      _require_nexus: false
      _save_requirements: true
      _service_transport: null
      _service_wait: 30.0
      _start_datetime: '20231003_182241'
      _start_time: 1696328561.0564861
      _stats_pid: 28520
      _stats_sample_rate_seconds: 2.0
      _stats_samples_to_average: 15
      _stats_join_assets: true
      _stats_neuron_monitor_config_path: null
      _stats_open_metrics_endpoints: null
      _stats_open_metrics_filters:
      - .*
      _stats_disk_paths:
      - /
      _tmp_code_dir: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\tmp\code
      _tracelog: null
      _unsaved_keys: null
      _windows: true
      allow_val_change: null
      anonymous: null
      api_key: null
      azure_account_url_to_access_key: null
      base_url: https://api.wandb.ai
      code_dir: null
      colab_url: null
      config_paths: null
      console: wrap
      deployment: cloud
      disable_code: false
      disable_git: false
      disable_hints: null
      disable_job_creation: false
      disabled: false
      docker: null
      email: mohamedragab1992@gmail.com
      entity: mohamed_ragab
      files_dir: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\files
      force: null
      git_commit: 55741859865af63df65682c6e153ef7f645fd2d2
      git_remote: origin
      git_remote_url: https://github.com/EDWARD-mononym/CDA
      git_root: null
      heartbeat_seconds: 30
      host: DESKTOP-QA7UUCC
      ignore_globs: []
      init_timeout: 90.0
      is_local: false
      job_name: null
      job_source: null
      label_disable: null
      launch: null
      launch_config_path: null
      log_dir: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\logs
      log_internal: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\logs\debug-internal.log
      log_symlink_internal: D:\Continual_DA\wandb\debug-internal.log
      log_symlink_user: D:\Continual_DA\wandb\debug.log
      log_user: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\logs\debug.log
      login_timeout: null
      mode: online
      notebook_name: null
      problem: fatal
      program: D:\Continual_DA\main_sweep_wandb.py
      program_abspath: D:\Continual_DA\main_sweep_wandb.py
      program_relpath: main_sweep_wandb.py
      project: test_project
      project_url: https://wandb.ai/mohamed_ragab/test_project
      quiet: null
      reinit: null
      relogin: null
      resume: null
      resume_fname: D:\Continual_DA\wandb\wandb-resume.json
      resumed: false
      root_dir: D:\Continual_DA
      run_group: null
      run_id: rzo6wyja
      run_job_type: null
      run_mode: run
      run_name: snowy-sweep-1
      run_notes: null
      run_tags: null
      run_url: https://wandb.ai/mohamed_ragab/test_project/runs/rzo6wyja
      sagemaker_disable: null
      save_code: null
      settings_system: C:\Users\Mohamed Ragab\.config\wandb\settings
      settings_workspace: D:\Continual_DA\wandb\settings
      show_colors: null
      show_emoji: null
      show_errors: true
      show_info: true
      show_warnings: true
      silent: false
      start_method: null
      strict: null
      summary_errors: null
      summary_timeout: 60
      summary_warnings: 5
      sweep_id: 1jytq3wz
      sweep_param_path: D:\Continual_DA\wandb\sweep-1jytq3wz\config-rzo6wyja.yaml
      sweep_url: https://wandb.ai/mohamed_ragab/test_project/sweeps/1jytq3wz
      symlink: false
      sync_dir: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja
      sync_file: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\run-rzo6wyja.wandb
      sync_symlink_latest: D:\Continual_DA\wandb\latest-run
      system_sample: 15
      system_sample_seconds: 2
      table_raise_on_max_row_limit_exceeded: false
      timespec: '20231003_182241'
      tmp_dir: D:\Continual_DA\wandb\run-20231003_182241-rzo6wyja\tmp
      username: Mohamed Ragab
      wandb_dir: D:\Continual_DA\wandb\
    _artifact_callback: wandb.sdk.wandb_run.Run._config_artifact_callback
    _wandb: {}
_locked:
  desc: null
  value:
    coral_wt: 0
    lr: 0
_users:
  desc: null
  value:
    sweep: 0
_users_inv:
  desc: null
  value:
    '0': sweep
_users_cnt:
  desc: null
  value: 1
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value:
    _args: []
    _aws_lambda: false
    _async_upload_concurrency_limit: null
    _cli_only_mode: null
    _colab: false
    _cuda: null
    _disable_meta: false
    _disable_service: false
    _disable_setproctitle: false
    _disable_stats: false
    _disable_viewer: null
    _disable_machine_info: false
    _except_exit: true
    _executable: C:\Users\Mohamed Ragab\.conda\envs\dl_work\python.exe
    _extra_http_headers: null
    _file_stream_retry_max: 125
    _file_stream_retry_wait_min_seconds: 2
    _file_stream_retry_wait_max_seconds: 60
    _file_stream_timeout_seconds: 180
    _file_uploader_retry_max: 10
    _file_uploader_retry_wait_min_seconds: 2
    _file_uploader_retry_wait_max_seconds: 60
    _file_uploader_timeout_seconds: 0
    _flow_control_custom: false
    _flow_control_disabled: false
    _graphql_retry_max: 10
    _graphql_retry_wait_min_seconds: 2
    _graphql_retry_wait_max_seconds: 60
    _graphql_timeout_seconds: 30
    _internal_check_process: 8.0
    _internal_queue_timeout: 2.0
    _ipython: false
    _jupyter: false
    _jupyter_name: null
    _jupyter_path: null
    _jupyter_root: null
    _kaggle: false
    _live_policy_rate_limit: null
    _live_policy_wait_time: null
    _log_level: 10
    _network_buffer: null
    _noop: false
    _notebook: false
    _offline: false
    _sync: false
    _os: Windows-10-10.0.19045-SP0
    _platform: windows
    _proxies: null
    _python: 3.9.13
    _runqueue_item_id: null
    _require_nexus: false
    _save_requirements: true
    _service_transport: null
    _service_wait: 30.0
    _start_datetime: '20231003_182308'
    _start_time: 1696328588.0817826
    _stats_pid: 28520
    _stats_sample_rate_seconds: 2.0
    _stats_samples_to_average: 15
    _stats_join_assets: true
    _stats_neuron_monitor_config_path: null
    _stats_open_metrics_endpoints: null
    _stats_open_metrics_filters:
    - .*
    _stats_disk_paths:
    - /
    _tmp_code_dir: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\tmp\code
    _tracelog: null
    _unsaved_keys: null
    _windows: true
    allow_val_change: null
    anonymous: null
    api_key: null
    azure_account_url_to_access_key: null
    base_url: https://api.wandb.ai
    code_dir: null
    colab_url: null
    config_paths: null
    console: wrap
    deployment: cloud
    disable_code: false
    disable_git: false
    disable_hints: null
    disable_job_creation: false
    disabled: false
    docker: null
    email: mohamedragab1992@gmail.com
    entity: mohamed_ragab
    files_dir: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\files
    force: null
    git_commit: 55741859865af63df65682c6e153ef7f645fd2d2
    git_remote: origin
    git_remote_url: https://github.com/EDWARD-mononym/CDA
    git_root: null
    heartbeat_seconds: 30
    host: DESKTOP-QA7UUCC
    ignore_globs: []
    init_timeout: 90.0
    is_local: false
    job_name: null
    job_source: null
    label_disable: null
    launch: null
    launch_config_path: null
    log_dir: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\logs
    log_internal: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\logs\debug-internal.log
    log_symlink_internal: D:\Continual_DA\wandb\debug-internal.log
    log_symlink_user: D:\Continual_DA\wandb\debug.log
    log_user: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\logs\debug.log
    login_timeout: null
    mode: online
    notebook_name: null
    problem: fatal
    program: D:\Continual_DA\main_sweep_wandb.py
    program_abspath: D:\Continual_DA\main_sweep_wandb.py
    program_relpath: main_sweep_wandb.py
    project: test_project
    project_url: https://wandb.ai/mohamed_ragab/test_project
    quiet: null
    reinit: null
    relogin: null
    resume: null
    resume_fname: D:\Continual_DA\wandb\wandb-resume.json
    resumed: false
    root_dir: D:\Continual_DA
    run_group: null
    run_id: vlai8dsh
    run_job_type: null
    run_mode: run
    run_name: rare-sweep-2
    run_notes: null
    run_tags: null
    run_url: https://wandb.ai/mohamed_ragab/test_project/runs/vlai8dsh
    sagemaker_disable: null
    save_code: null
    settings_system: C:\Users\Mohamed Ragab\.config\wandb\settings
    settings_workspace: D:\Continual_DA\wandb\settings
    show_colors: null
    show_emoji: null
    show_errors: true
    show_info: true
    show_warnings: true
    silent: false
    start_method: null
    strict: null
    summary_errors: null
    summary_timeout: 60
    summary_warnings: 5
    sweep_id: 1jytq3wz
    sweep_param_path: D:\Continual_DA\wandb\sweep-1jytq3wz\config-vlai8dsh.yaml
    sweep_url: https://wandb.ai/mohamed_ragab/test_project/sweeps/1jytq3wz
    symlink: false
    sync_dir: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh
    sync_file: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\run-vlai8dsh.wandb
    sync_symlink_latest: D:\Continual_DA\wandb\latest-run
    system_sample: 15
    system_sample_seconds: 2
    table_raise_on_max_row_limit_exceeded: false
    timespec: '20231003_182308'
    tmp_dir: D:\Continual_DA\wandb\run-20231003_182308-vlai8dsh\tmp
    username: Mohamed Ragab
    wandb_dir: D:\Continual_DA\wandb\
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696328603.585698
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
