wandb_version: 1

_fields:
  desc: null
  value:
    Dataset_Name: PU_Real
    Scenarios:
    - Normal
    - Rotate
    - Load
    - Radial
    num_class: 5
    input_channel: 1
    Backbone_Type: CNN
    feature_length: 5
    hidden_channels: 64
    kernel_size: 5
    stride: 1
    dropout: 0.5
    output_channels: 128
    hidden_layers: 5
    Classifier_Type: Classifier
    input_size: 1280
    n_epoch: 1
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
    step_size: 50
    gamma: 0.5
    Method: DeepCORAL
    coral_wt: 0.1
_locked:
  desc: null
  value: false
_type_safe:
  desc: null
  value: true
_convert_dict:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696404017.821801
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
