wandb_version: 1

Dataset_Name:
  desc: null
  value: PU_Real
Scenarios:
  desc: null
  value:
  - - Normal
    - Rotate
    - Load
    - Radial
num_class:
  desc: null
  value: 5
input_channel:
  desc: null
  value: 1
Backbone_Type:
  desc: null
  value: CNN
feature_length:
  desc: null
  value: 5
hidden_channels:
  desc: null
  value: 64
kernel_size:
  desc: null
  value: 5
stride:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.5
output_channels:
  desc: null
  value: 128
hidden_layers:
  desc: null
  value: 5
Classifier_Type:
  desc: null
  value: Classifier
input_size:
  desc: null
  value: 640
n_epoch:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0001
step_size:
  desc: null
  value: 50
gamma:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696384158.074589
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
